package edu.pitt.sis.exp.colfusion.dal.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionDnameMetaData generated by hbm2java
 */
public class ColfusionDnameMetaData implements java.io.Serializable {

	private Integer metaId;
	private int cid;
	private String type;
	private String value;
	private int sid;

	public ColfusionDnameMetaData() {
	}

	public ColfusionDnameMetaData(int cid, String type, String value, int sid) {
		this.cid = cid;
		this.type = type;
		this.value = value;
		this.sid = sid;
	}

	public Integer getMetaId() {
		return this.metaId;
	}

	public void setMetaId(Integer metaId) {
		this.metaId = metaId;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

}
