package edu.pitt.sis.exp.colfusion.dal.orm;

// Generated Dec 13, 2014 7:22:59 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ColfusionTableChangeLogId generated by hbm2java
 */
public class ColfusionTableChangeLogId implements java.io.Serializable {

	private int sid;
	private String tableName;
	private Date startChangeTime;
	private Date endChangeTime;
	private String operatedUser;

	public ColfusionTableChangeLogId() {
	}

	public ColfusionTableChangeLogId(int sid, String tableName,
			Date startChangeTime, String operatedUser) {
		this.sid = sid;
		this.tableName = tableName;
		this.startChangeTime = startChangeTime;
		this.operatedUser = operatedUser;
	}

	public ColfusionTableChangeLogId(int sid, String tableName,
			Date startChangeTime, Date endChangeTime, String operatedUser) {
		this.sid = sid;
		this.tableName = tableName;
		this.startChangeTime = startChangeTime;
		this.endChangeTime = endChangeTime;
		this.operatedUser = operatedUser;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public Date getStartChangeTime() {
		return this.startChangeTime;
	}

	public void setStartChangeTime(Date startChangeTime) {
		this.startChangeTime = startChangeTime;
	}

	public Date getEndChangeTime() {
		return this.endChangeTime;
	}

	public void setEndChangeTime(Date endChangeTime) {
		this.endChangeTime = endChangeTime;
	}

	public String getOperatedUser() {
		return this.operatedUser;
	}

	public void setOperatedUser(String operatedUser) {
		this.operatedUser = operatedUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ColfusionTableChangeLogId))
			return false;
		ColfusionTableChangeLogId castOther = (ColfusionTableChangeLogId) other;

		return (this.getSid() == castOther.getSid())
				&& ((this.getTableName() == castOther.getTableName()) || (this
						.getTableName() != null
						&& castOther.getTableName() != null && this
						.getTableName().equals(castOther.getTableName())))
				&& ((this.getStartChangeTime() == castOther
						.getStartChangeTime()) || (this.getStartChangeTime() != null
						&& castOther.getStartChangeTime() != null && this
						.getStartChangeTime().equals(
								castOther.getStartChangeTime())))
				&& ((this.getEndChangeTime() == castOther.getEndChangeTime()) || (this
						.getEndChangeTime() != null
						&& castOther.getEndChangeTime() != null && this
						.getEndChangeTime()
						.equals(castOther.getEndChangeTime())))
				&& ((this.getOperatedUser() == castOther.getOperatedUser()) || (this
						.getOperatedUser() != null
						&& castOther.getOperatedUser() != null && this
						.getOperatedUser().equals(castOther.getOperatedUser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSid();
		result = 37 * result
				+ (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37
				* result
				+ (getStartChangeTime() == null ? 0 : this.getStartChangeTime()
						.hashCode());
		result = 37
				* result
				+ (getEndChangeTime() == null ? 0 : this.getEndChangeTime()
						.hashCode());
		result = 37
				* result
				+ (getOperatedUser() == null ? 0 : this.getOperatedUser()
						.hashCode());
		return result;
	}

}
