package edu.pitt.sis.exp.colfusion.dal.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ColfusionCanvases generated by hbm2java
 */
public class ColfusionCanvases implements java.io.Serializable {

   private Integer vid;
   private String name;
   private String note;
   private Date mdate;
   private Date cdate;
   private Integer privilege;
   
   private ColfusionUsers users;
   private Set<ColfusionStory> storySet = new HashSet(0);

   public ColfusionCanvases() {
   }

   public ColfusionCanvases(Date mdate, Date cdate) {
     this.mdate = mdate;
     this.cdate = cdate;
   }

   public ColfusionCanvases(ColfusionUsers users, String name,
     String note, Date mdate, Date cdate, Integer privilege) {
     this.users = users;
     this.name = name;
     this.note = note;
     this.mdate = mdate;
     this.cdate = cdate;
     this.privilege = privilege;
   }
   
   public ColfusionCanvases(Integer vid, Set<ColfusionStory> storySet, ColfusionUsers users, String name,
		     String note, Date mdate, Date cdate, Integer privilege) {
	   		 this.vid = vid;
		     this.users = users;
		     this.storySet = storySet;
		     this.name = name;
		     this.note = note;
		     this.mdate = mdate;
		     this.cdate = cdate;
		     this.privilege = privilege;
   }

   public Integer getVid() {
     return this.vid;
   }

   public void setVid(Integer vid) {
     this.vid = vid;
   }

   public ColfusionUsers getUsers() {
     return this.users;
   }

   public void setUsers(ColfusionUsers users) {
     this.users = users;
   }

   public String getName() {
     return this.name;
   }

   public void setName(String name) {
     this.name = name;
  }

   public String getNote() {
     return this.note;
   }

   public void setNote(String note) {
     this.note = note;
  }

   public Date getMdate() {
     return this.mdate;
  }

   public void setMdate(Date mdate) {
     this.mdate = mdate;
  }

   public Date getCdate() {
     return this.cdate;
  }

   public void setCdate(Date cdate) {
     this.cdate = cdate;
  }

   public Integer getPrivilege() {
     return this.privilege;
  }

   public void setPrivilege(Integer privilege) {
     this.privilege = privilege;
  }

public Set<ColfusionStory> getStorySet() {
	return storySet;
}

public void setStorySet(Set<ColfusionStory> storySet) {
	this.storySet = storySet;
}
  

}

