package edu.pitt.sis.exp.colfusion.dal.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionSavedLinks generated by hbm2java
 */
public class ColfusionSavedLinks implements java.io.Serializable {

	private Integer savedId;
	private int savedUserId;
	private int savedLinkId;
	private String savedPrivacy;

	public ColfusionSavedLinks() {
	}

	public ColfusionSavedLinks(int savedUserId, int savedLinkId,
			String savedPrivacy) {
		this.savedUserId = savedUserId;
		this.savedLinkId = savedLinkId;
		this.savedPrivacy = savedPrivacy;
	}

	public Integer getSavedId() {
		return this.savedId;
	}

	public void setSavedId(Integer savedId) {
		this.savedId = savedId;
	}

	public int getSavedUserId() {
		return this.savedUserId;
	}

	public void setSavedUserId(int savedUserId) {
		this.savedUserId = savedUserId;
	}

	public int getSavedLinkId() {
		return this.savedLinkId;
	}

	public void setSavedLinkId(int savedLinkId) {
		this.savedLinkId = savedLinkId;
	}

	public String getSavedPrivacy() {
		return this.savedPrivacy;
	}

	public void setSavedPrivacy(String savedPrivacy) {
		this.savedPrivacy = savedPrivacy;
	}

}
