package edu.pitt.sis.exp.colfusion.dal.orm;

// Generated Dec 13, 2014 7:22:59 PM by Hibernate Tools 4.0.0

/**
 * ColfusionTableChangeLog generated by hbm2java
 */
public class ColfusionTableChangeLog implements java.io.Serializable {

	private ColfusionTableChangeLogId id;

	public ColfusionTableChangeLog() {
	}

	public ColfusionTableChangeLog(ColfusionTableChangeLogId id) {
		this.id = id;
	}

	public ColfusionTableChangeLogId getId() {
		return this.id;
	}

	public void setId(ColfusionTableChangeLogId id) {
		this.id = id;
	}

}
