package edu.pitt.sis.exp.colfusion.dal.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionRelationshipsColumnsId generated by hbm2java
 */
public class ColfusionRelationshipsColumnsId implements java.io.Serializable {

	private int relId;
	private String clFrom;
	private String clTo;

	public ColfusionRelationshipsColumnsId() {
	}

	public ColfusionRelationshipsColumnsId(int relId, String clFrom, String clTo) {
		this.relId = relId;
		this.clFrom = clFrom;
		this.clTo = clTo;
	}

	public int getRelId() {
		return this.relId;
	}

	public void setRelId(int relId) {
		this.relId = relId;
	}

	public String getClFrom() {
		return this.clFrom;
	}

	public void setClFrom(String clFrom) {
		this.clFrom = clFrom;
	}

	public String getClTo() {
		return this.clTo;
	}

	public void setClTo(String clTo) {
		this.clTo = clTo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ColfusionRelationshipsColumnsId))
			return false;
		ColfusionRelationshipsColumnsId castOther = (ColfusionRelationshipsColumnsId) other;

		return (this.getRelId() == castOther.getRelId())
				&& ((this.getClFrom() == castOther.getClFrom()) || (this
						.getClFrom() != null && castOther.getClFrom() != null && this
						.getClFrom().equals(castOther.getClFrom())))
				&& ((this.getClTo() == castOther.getClTo()) || (this.getClTo() != null
						&& castOther.getClTo() != null && this.getClTo()
						.equals(castOther.getClTo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRelId();
		result = 37 * result
				+ (getClFrom() == null ? 0 : this.getClFrom().hashCode());
		result = 37 * result
				+ (getClTo() == null ? 0 : this.getClTo().hashCode());
		return result;
	}

}
