package edu.pitt.sis.exp.colfusion.dal.orm;
// default package
// Generated Oct 6, 2014 2:04:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ColfusionLicense generated by hbm2java
 */
public class ColfusionLicense implements java.io.Serializable {

	private Integer licenseId;
	private String licenseName;
	private String licenseDes;
	private String licenseUrl;
	private Set colfusionSourceinfos = new HashSet(0);

	public ColfusionLicense() {
	}

	public ColfusionLicense(String licenseName) {
		this.licenseName = licenseName;
	}

	public ColfusionLicense(String licenseName, String licenseDes,
			String licenseUrl, Set colfusionSourceinfos) {
		this.licenseName = licenseName;
		this.licenseDes = licenseDes;
		this.licenseUrl = licenseUrl;
		this.colfusionSourceinfos = colfusionSourceinfos;
	}

	public Integer getLicenseId() {
		return this.licenseId;
	}

	public void setLicenseId(Integer licenseId) {
		this.licenseId = licenseId;
	}

	public String getLicenseName() {
		return this.licenseName;
	}

	public void setLicenseName(String licenseName) {
		this.licenseName = licenseName;
	}

	public String getLicenseDes() {
		return this.licenseDes;
	}

	public void setLicenseDes(String licenseDes) {
		this.licenseDes = licenseDes;
	}

	public String getLicenseUrl() {
		return this.licenseUrl;
	}

	public void setLicenseUrl(String licenseUrl) {
		this.licenseUrl = licenseUrl;
	}

	public Set getColfusionSourceinfos() {
		return this.colfusionSourceinfos;
	}

	public void setColfusionSourceinfos(Set colfusionSourceinfos) {
		this.colfusionSourceinfos = colfusionSourceinfos;
	}

}
