package edu.pitt.sis.exp.colfusion.dal.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionMiscData generated by hbm2java
 */
public class ColfusionMiscData implements java.io.Serializable {

	private String name;
	private String data;

	public ColfusionMiscData() {
	}

	public ColfusionMiscData(String name) {
		this.name = name;
	}

	public ColfusionMiscData(String name, String data) {
		this.name = name;
		this.data = data;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

}
