package edu.pitt.sis.exp.colfusion.dal.orm;

// Generated Dec 13, 2014 7:22:59 PM by Hibernate Tools 4.0.0

/**
 * ColfusionOpenrefineHistoryHelper generated by hbm2java
 */
public class ColfusionOpenrefineHistoryHelper implements java.io.Serializable {

	private ColfusionOpenrefineHistoryHelperId id;

	public ColfusionOpenrefineHistoryHelper() {
	}

	public ColfusionOpenrefineHistoryHelper(
			ColfusionOpenrefineHistoryHelperId id) {
		this.id = id;
	}

	public ColfusionOpenrefineHistoryHelperId getId() {
		return this.id;
	}

	public void setId(ColfusionOpenrefineHistoryHelperId id) {
		this.id = id;
	}

}
