package edu.pitt.sis.exp.colfusion.dal.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionCharts generated by hbm2java
 */
public class ColfusionCharts implements java.io.Serializable {

	private Integer cid;
	private ColfusionStory story;
	private String name;
	private String type;
	private String did;
	private String dname;
	private String tname;
	private String columns;
	
	
	public ColfusionCharts() {
		
	}
	
	public ColfusionCharts(String type, String did, String dname, String tname, String columns, ColfusionStory story){
		this.type = type;
		this.did = did;
		this.dname = dname;
		this.tname = tname;
		this.columns = columns;
		this.story = story;
	}
	
	public ColfusionCharts(Integer cid, ColfusionStory story, String name, String type,
			String did, String dname, String tname, String columns) {
		super();
		this.cid = cid;
		this.story = story;
		this.name = name;
		this.type = type;
		this.did = did;
		this.dname = dname;
		this.tname = tname;
		this.columns = columns;
	}

	
	public Integer getCid() {
		return cid;
	}
	public void setCid(Integer cid) {
		this.cid = cid;
	}
	public ColfusionStory getStory() {
		return story;
	}
	public void setStory(ColfusionStory story) {
		this.story = story;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getDid() {
		return did;
	}
	public void setDid(String did) {
		this.did = did;
	}
	public String getDname() {
		return dname;
	}
	public void setDname(String dname) {
		this.dname = dname;
	}
	public String getTname() {
		return tname;
	}
	public void setTname(String tname) {
		this.tname = tname;
	}
	public String getColumns() {
		return columns;
	}
	public void setColumns(String columns) {
		this.columns = columns;
	}
}
