package edu.pitt.sis.exp.colfusion.dal.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionSourceinfoUserId generated by hbm2java
 */
public class ColfusionSourceinfoUserId implements java.io.Serializable {

	private int sid;
	private int uid;

	public ColfusionSourceinfoUserId() {
	}

	public ColfusionSourceinfoUserId(int sid, int uid) {
		this.sid = sid;
		this.uid = uid;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ColfusionSourceinfoUserId))
			return false;
		ColfusionSourceinfoUserId castOther = (ColfusionSourceinfoUserId) other;

		return (this.getSid() == castOther.getSid())
				&& (this.getUid() == castOther.getUid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSid();
		result = 37 * result + this.getUid();
		return result;
	}

}
