package edu.pitt.sis.exp.colfusion.dal.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionColumnTableInfo generated by hbm2java
 */
public class ColfusionColumnTableInfo implements java.io.Serializable {

	private int cid;
	private ColfusionDnameinfo colfusionDnameinfo;
	private String tableName;
	private String dbTableName;

	public ColfusionColumnTableInfo() {
	}

	public ColfusionColumnTableInfo(final ColfusionDnameinfo colfusionDnameinfo,
			final String tableName, final String dbTableName) {
		this.colfusionDnameinfo = colfusionDnameinfo;
		this.tableName = tableName;
		this.dbTableName = dbTableName;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(final int cid) {
		this.cid = cid;
	}

	public ColfusionDnameinfo getColfusionDnameinfo() {
		return this.colfusionDnameinfo;
	}

	public void setColfusionDnameinfo(final ColfusionDnameinfo colfusionDnameinfo) {
		this.colfusionDnameinfo = colfusionDnameinfo;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(final String tableName) {
		this.tableName = tableName;
	}
	
	public String getDbTableName() {
		return this.dbTableName;
	}

	public void setDbTableName(final String dbTableName) {
		this.dbTableName = dbTableName;
	}

}
