package edu.pitt.sis.exp.colfusion.dal.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

/**
 * Statonverdicts generated by hbm2java
 */
public class Statonverdicts implements java.io.Serializable {

	private StatonverdictsId id;

	public Statonverdicts() {
	}

	public Statonverdicts(StatonverdictsId id) {
		this.id = id;
	}

	public StatonverdictsId getId() {
		return this.id;
	}

	public void setId(StatonverdictsId id) {
		this.id = id;
	}

}
