package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionPentahoLogPerformance generated by hbm2java
 */
public class ColfusionPentahoLogPerformance implements java.io.Serializable {

	private ColfusionPentahoLogPerformanceId id;

	public ColfusionPentahoLogPerformance() {
	}

	public ColfusionPentahoLogPerformance(ColfusionPentahoLogPerformanceId id) {
		this.id = id;
	}

	public ColfusionPentahoLogPerformanceId getId() {
		return this.id;
	}

	public void setId(ColfusionPentahoLogPerformanceId id) {
		this.id = id;
	}

}
