package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionTagCache generated by hbm2java
 */
public class ColfusionTagCache implements java.io.Serializable {

	private ColfusionTagCacheId id;

	public ColfusionTagCache() {
	}

	public ColfusionTagCache(ColfusionTagCacheId id) {
		this.id = id;
	}

	public ColfusionTagCacheId getId() {
		return this.id;
	}

	public void setId(ColfusionTagCacheId id) {
		this.id = id;
	}

}
