package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated 2014-5-12 21:35:22 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionColumntableinfo generated by hbm2java
 */
public class ColfusionColumntableinfo implements java.io.Serializable {

	private int cid;
	private ColfusionDnameinfo colfusionDnameinfo;
	private String tableName;

	public ColfusionColumntableinfo() {
	}

	public ColfusionColumntableinfo(ColfusionDnameinfo colfusionDnameinfo,
			String tableName) {
		this.colfusionDnameinfo = colfusionDnameinfo;
		this.tableName = tableName;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public ColfusionDnameinfo getColfusionDnameinfo() {
		return this.colfusionDnameinfo;
	}

	public void setColfusionDnameinfo(ColfusionDnameinfo colfusionDnameinfo) {
		this.colfusionDnameinfo = colfusionDnameinfo;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

}
