package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Apr 26, 2014 9:30:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ColfusionMessages generated by hbm2java
 */
public class ColfusionMessages implements java.io.Serializable {

	private Integer idMsg;
	private String title;
	private String body;
	private int sender;
	private int receiver;
	private int senderLevel;
	private int readed;
	private Date date;

	public ColfusionMessages() {
	}

	public ColfusionMessages(int sender, int receiver, int senderLevel,
			int readed, Date date) {
		this.sender = sender;
		this.receiver = receiver;
		this.senderLevel = senderLevel;
		this.readed = readed;
		this.date = date;
	}

	public ColfusionMessages(String title, String body, int sender,
			int receiver, int senderLevel, int readed, Date date) {
		this.title = title;
		this.body = body;
		this.sender = sender;
		this.receiver = receiver;
		this.senderLevel = senderLevel;
		this.readed = readed;
		this.date = date;
	}

	public Integer getIdMsg() {
		return this.idMsg;
	}

	public void setIdMsg(Integer idMsg) {
		this.idMsg = idMsg;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public int getSender() {
		return this.sender;
	}

	public void setSender(int sender) {
		this.sender = sender;
	}

	public int getReceiver() {
		return this.receiver;
	}

	public void setReceiver(int receiver) {
		this.receiver = receiver;
	}

	public int getSenderLevel() {
		return this.senderLevel;
	}

	public void setSenderLevel(int senderLevel) {
		this.senderLevel = senderLevel;
	}

	public int getReaded() {
		return this.readed;
	}

	public void setReaded(int readed) {
		this.readed = readed;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
