package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Apr 26, 2014 9:30:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ColfusionTagsId generated by hbm2java
 */
public class ColfusionTagsId implements java.io.Serializable {

	private int tagLinkId;
	private String tagLang;
	private Date tagDate;
	private String tagWords;

	public ColfusionTagsId() {
	}

	public ColfusionTagsId(int tagLinkId, Date tagDate) {
		this.tagLinkId = tagLinkId;
		this.tagDate = tagDate;
	}

	public ColfusionTagsId(int tagLinkId, String tagLang, Date tagDate,
			String tagWords) {
		this.tagLinkId = tagLinkId;
		this.tagLang = tagLang;
		this.tagDate = tagDate;
		this.tagWords = tagWords;
	}

	public int getTagLinkId() {
		return this.tagLinkId;
	}

	public void setTagLinkId(int tagLinkId) {
		this.tagLinkId = tagLinkId;
	}

	public String getTagLang() {
		return this.tagLang;
	}

	public void setTagLang(String tagLang) {
		this.tagLang = tagLang;
	}

	public Date getTagDate() {
		return this.tagDate;
	}

	public void setTagDate(Date tagDate) {
		this.tagDate = tagDate;
	}

	public String getTagWords() {
		return this.tagWords;
	}

	public void setTagWords(String tagWords) {
		this.tagWords = tagWords;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ColfusionTagsId))
			return false;
		ColfusionTagsId castOther = (ColfusionTagsId) other;

		return (this.getTagLinkId() == castOther.getTagLinkId())
				&& ((this.getTagLang() == castOther.getTagLang()) || (this
						.getTagLang() != null && castOther.getTagLang() != null && this
						.getTagLang().equals(castOther.getTagLang())))
				&& ((this.getTagDate() == castOther.getTagDate()) || (this
						.getTagDate() != null && castOther.getTagDate() != null && this
						.getTagDate().equals(castOther.getTagDate())))
				&& ((this.getTagWords() == castOther.getTagWords()) || (this
						.getTagWords() != null
						&& castOther.getTagWords() != null && this
						.getTagWords().equals(castOther.getTagWords())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTagLinkId();
		result = 37 * result
				+ (getTagLang() == null ? 0 : this.getTagLang().hashCode());
		result = 37 * result
				+ (getTagDate() == null ? 0 : this.getTagDate().hashCode());
		result = 37 * result
				+ (getTagWords() == null ? 0 : this.getTagWords().hashCode());
		return result;
	}

}
