package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Feb 24, 2014 10:00:48 PM by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionShares generated by hbm2java
 */
public class ColfusionShares implements java.io.Serializable {

	private ColfusionSharesId id;
	private ColfusionUsers colfusionUsers;
	private ColfusionCanvases colfusionCanvases;

	public ColfusionShares() {
	}

	public ColfusionShares(ColfusionSharesId id) {
		this.id = id;
	}

	public ColfusionShares(ColfusionSharesId id, ColfusionUsers colfusionUsers,
			ColfusionCanvases colfusionCanvases) {
		this.id = id;
		this.colfusionUsers = colfusionUsers;
		this.colfusionCanvases = colfusionCanvases;
	}

	public ColfusionSharesId getId() {
		return this.id;
	}

	public void setId(ColfusionSharesId id) {
		this.id = id;
	}

	public ColfusionUsers getColfusionUsers() {
		return this.colfusionUsers;
	}

	public void setColfusionUsers(ColfusionUsers colfusionUsers) {
		this.colfusionUsers = colfusionUsers;
	}

	public ColfusionCanvases getColfusionCanvases() {
		return this.colfusionCanvases;
	}

	public void setColfusionCanvases(ColfusionCanvases colfusionCanvases) {
		this.colfusionCanvases = colfusionCanvases;
	}

}
