package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Feb 20, 2014 5:07:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ColfusionVotes generated by hbm2java
 */
public class ColfusionVotes implements java.io.Serializable {

	private Integer voteId;
	private String voteType;
	private Date voteDate;
	private int voteLinkId;
	private int voteUserId;
	private short voteValue;
	private Integer voteKarma;
	private String voteIp;

	public ColfusionVotes() {
	}

	public ColfusionVotes(String voteType, Date voteDate, int voteLinkId,
			int voteUserId, short voteValue) {
		this.voteType = voteType;
		this.voteDate = voteDate;
		this.voteLinkId = voteLinkId;
		this.voteUserId = voteUserId;
		this.voteValue = voteValue;
	}

	public ColfusionVotes(String voteType, Date voteDate, int voteLinkId,
			int voteUserId, short voteValue, Integer voteKarma, String voteIp) {
		this.voteType = voteType;
		this.voteDate = voteDate;
		this.voteLinkId = voteLinkId;
		this.voteUserId = voteUserId;
		this.voteValue = voteValue;
		this.voteKarma = voteKarma;
		this.voteIp = voteIp;
	}

	public Integer getVoteId() {
		return this.voteId;
	}

	public void setVoteId(Integer voteId) {
		this.voteId = voteId;
	}

	public String getVoteType() {
		return this.voteType;
	}

	public void setVoteType(String voteType) {
		this.voteType = voteType;
	}

	public Date getVoteDate() {
		return this.voteDate;
	}

	public void setVoteDate(Date voteDate) {
		this.voteDate = voteDate;
	}

	public int getVoteLinkId() {
		return this.voteLinkId;
	}

	public void setVoteLinkId(int voteLinkId) {
		this.voteLinkId = voteLinkId;
	}

	public int getVoteUserId() {
		return this.voteUserId;
	}

	public void setVoteUserId(int voteUserId) {
		this.voteUserId = voteUserId;
	}

	public short getVoteValue() {
		return this.voteValue;
	}

	public void setVoteValue(short voteValue) {
		this.voteValue = voteValue;
	}

	public Integer getVoteKarma() {
		return this.voteKarma;
	}

	public void setVoteKarma(Integer voteKarma) {
		this.voteKarma = voteKarma;
	}

	public String getVoteIp() {
		return this.voteIp;
	}

	public void setVoteIp(String voteIp) {
		this.voteIp = voteIp;
	}

}
