package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Feb 25, 2014 9:55:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionNotificationsUnread generated by hbm2java
 */
public class ColfusionNotificationsUnread implements java.io.Serializable {

	private ColfusionNotificationsUnreadId id;
	private ColfusionNotifications colfusionNotifications;

	public ColfusionNotificationsUnread() {
	}

	public ColfusionNotificationsUnread(ColfusionNotificationsUnreadId id,
			ColfusionNotifications colfusionNotifications) {
		this.id = id;
		this.colfusionNotifications = colfusionNotifications;
	}

	public ColfusionNotificationsUnreadId getId() {
		return this.id;
	}

	public void setId(ColfusionNotificationsUnreadId id) {
		this.id = id;
	}

	public ColfusionNotifications getColfusionNotifications() {
		return this.colfusionNotifications;
	}

	public void setColfusionNotifications(
			ColfusionNotifications colfusionNotifications) {
		this.colfusionNotifications = colfusionNotifications;
	}

}
