package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Feb 20, 2014 5:07:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionPentahoLogLoggingChannels generated by hbm2java
 */
public class ColfusionPentahoLogLoggingChannels implements java.io.Serializable {

	private ColfusionPentahoLogLoggingChannelsId id;

	public ColfusionPentahoLogLoggingChannels() {
	}

	public ColfusionPentahoLogLoggingChannels(
			ColfusionPentahoLogLoggingChannelsId id) {
		this.id = id;
	}

	public ColfusionPentahoLogLoggingChannelsId getId() {
		return this.id;
	}

	public void setId(ColfusionPentahoLogLoggingChannelsId id) {
		this.id = id;
	}

}
