package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Apr 26, 2014 9:30:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionAdditionalCategoriesId generated by hbm2java
 */
public class ColfusionAdditionalCategoriesId implements java.io.Serializable {

	private int acLinkId;
	private int acCatId;

	public ColfusionAdditionalCategoriesId() {
	}

	public ColfusionAdditionalCategoriesId(int acLinkId, int acCatId) {
		this.acLinkId = acLinkId;
		this.acCatId = acCatId;
	}

	public int getAcLinkId() {
		return this.acLinkId;
	}

	public void setAcLinkId(int acLinkId) {
		this.acLinkId = acLinkId;
	}

	public int getAcCatId() {
		return this.acCatId;
	}

	public void setAcCatId(int acCatId) {
		this.acCatId = acCatId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ColfusionAdditionalCategoriesId))
			return false;
		ColfusionAdditionalCategoriesId castOther = (ColfusionAdditionalCategoriesId) other;

		return (this.getAcLinkId() == castOther.getAcLinkId())
				&& (this.getAcCatId() == castOther.getAcCatId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAcLinkId();
		result = 37 * result + this.getAcCatId();
		return result;
	}

}
