package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionSourceinfoTableKtr generated by hbm2java
 */
public class ColfusionSourceinfoTableKtr implements java.io.Serializable {

	private ColfusionSourceinfoTableKtrId id;
	private ColfusionSourceinfo colfusionSourceinfo;
	private String pathToKtrfile;

	public ColfusionSourceinfoTableKtr() {
	}

	public ColfusionSourceinfoTableKtr(ColfusionSourceinfoTableKtrId id,
			ColfusionSourceinfo colfusionSourceinfo, String pathToKtrfile) {
		this.id = id;
		this.colfusionSourceinfo = colfusionSourceinfo;
		this.pathToKtrfile = pathToKtrfile;
	}

	public ColfusionSourceinfoTableKtrId getId() {
		return this.id;
	}

	public void setId(ColfusionSourceinfoTableKtrId id) {
		this.id = id;
	}

	public ColfusionSourceinfo getColfusionSourceinfo() {
		return this.colfusionSourceinfo;
	}

	public void setColfusionSourceinfo(ColfusionSourceinfo colfusionSourceinfo) {
		this.colfusionSourceinfo = colfusionSourceinfo;
	}

	public String getPathToKtrfile() {
		return this.pathToKtrfile;
	}

	public void setPathToKtrfile(String pathToKtrfile) {
		this.pathToKtrfile = pathToKtrfile;
	}

}
