package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Apr 26, 2014 9:30:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionPentahoLogTransformaion generated by hbm2java
 */
public class ColfusionPentahoLogTransformaion implements java.io.Serializable {

	private ColfusionPentahoLogTransformaionId id;

	public ColfusionPentahoLogTransformaion() {
	}

	public ColfusionPentahoLogTransformaion(
			ColfusionPentahoLogTransformaionId id) {
		this.id = id;
	}

	public ColfusionPentahoLogTransformaionId getId() {
		return this.id;
	}

	public void setId(ColfusionPentahoLogTransformaionId id) {
		this.id = id;
	}

}
