package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated May 7, 2014 10:39:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionLikes generated by hbm2java
 */
public class ColfusionLikes implements java.io.Serializable {

	private ColfusionLikesId id;

	public ColfusionLikes() {
	}

	public ColfusionLikes(ColfusionLikesId id) {
		this.id = id;
	}

	public ColfusionLikesId getId() {
		return this.id;
	}

	public void setId(ColfusionLikesId id) {
		this.id = id;
	}

}
