package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Feb 25, 2014 9:55:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionTags generated by hbm2java
 */
public class ColfusionTags implements java.io.Serializable {

	private ColfusionTagsId id;

	public ColfusionTags() {
	}

	public ColfusionTags(ColfusionTagsId id) {
		this.id = id;
	}

	public ColfusionTagsId getId() {
		return this.id;
	}

	public void setId(ColfusionTagsId id) {
		this.id = id;
	}

}
