package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated May 7, 2014 10:39:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ColfusionRelationshipsColumnsDataMathingRatios generated by hbm2java
 */
public class ColfusionRelationshipsColumnsDataMathingRatios implements
		java.io.Serializable {

	private ColfusionRelationshipsColumnsDataMathingRatiosId id;
	private ColfusionProcesses colfusionProcesses;
	private BigDecimal dataMatchingFromRatio;
	private BigDecimal dataMatchingToRatio;

	public ColfusionRelationshipsColumnsDataMathingRatios() {
	}

	public ColfusionRelationshipsColumnsDataMathingRatios(
			final ColfusionRelationshipsColumnsDataMathingRatiosId id,
			final ColfusionProcesses colfusionProcesses) {
		this.id = id;
		this.colfusionProcesses = colfusionProcesses;
	}

	public ColfusionRelationshipsColumnsDataMathingRatios(
			final ColfusionRelationshipsColumnsDataMathingRatiosId id,
			final ColfusionProcesses colfusionProcesses,
			final BigDecimal dataMatchingFromRatio, final BigDecimal dataMatchingToRatio) {
		this.id = id;
		this.colfusionProcesses = colfusionProcesses;
		this.dataMatchingFromRatio = dataMatchingFromRatio;
		this.dataMatchingToRatio = dataMatchingToRatio;
	}

	public ColfusionRelationshipsColumnsDataMathingRatiosId getId() {
		return this.id;
	}

	public void setId(final ColfusionRelationshipsColumnsDataMathingRatiosId id) {
		this.id = id;
	}

	public ColfusionProcesses getColfusionProcesses() {
		return this.colfusionProcesses;
	}

	public void setColfusionProcesses(final ColfusionProcesses colfusionProcesses) {
		this.colfusionProcesses = colfusionProcesses;
	}

	public BigDecimal getDataMatchingFromRatio() {
		return this.dataMatchingFromRatio;
	}

	public void setDataMatchingFromRatio(final BigDecimal dataMatchingFromRatio) {
		this.dataMatchingFromRatio = dataMatchingFromRatio;
	}

	public BigDecimal getDataMatchingToRatio() {
		return this.dataMatchingToRatio;
	}

	public void setDataMatchingToRatio(final BigDecimal dataMatchingToRatio) {
		this.dataMatchingToRatio = dataMatchingToRatio;
	}

}
