package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ColfusionLinks generated by hbm2java
 */
public class ColfusionLinks implements java.io.Serializable {

	private int linkId;
	private int linkAuthor;
	private String linkStatus;
	private int linkRandkey;
	private int linkVotes;
	private int linkReports;
	private int linkComments;
	private BigDecimal linkKarma;
	private Date linkModified;
	private Date linkDate;
	private Date linkPublishedDate;
	private int linkCategory;
	private int linkLang;
	private String linkUrl;
	private String linkUrlTitle;
	private String linkTitle;
	private String linkTitleUrl;
	private String linkContent;
	private String linkSummary;
	private String linkTags;
	private String linkField1;
	private String linkField2;
	private String linkField3;
	private String linkField4;
	private String linkField5;
	private String linkField6;
	private String linkField7;
	private String linkField8;
	private String linkField9;
	private String linkField10;
	private String linkField11;
	private String linkField12;
	private String linkField13;
	private String linkField14;
	private String linkField15;
	private int linkGroupId;
	private String linkGroupStatus;
	private int linkOut;

	public ColfusionLinks() {
	}

	public ColfusionLinks(int linkId, int linkAuthor, int linkRandkey,
			int linkVotes, int linkReports, int linkComments,
			BigDecimal linkKarma, Date linkModified, Date linkDate,
			Date linkPublishedDate, int linkCategory, int linkLang,
			int linkGroupId, String linkGroupStatus, int linkOut) {
		this.linkId = linkId;
		this.linkAuthor = linkAuthor;
		this.linkRandkey = linkRandkey;
		this.linkVotes = linkVotes;
		this.linkReports = linkReports;
		this.linkComments = linkComments;
		this.linkKarma = linkKarma;
		this.linkModified = linkModified;
		this.linkDate = linkDate;
		this.linkPublishedDate = linkPublishedDate;
		this.linkCategory = linkCategory;
		this.linkLang = linkLang;
		this.linkGroupId = linkGroupId;
		this.linkGroupStatus = linkGroupStatus;
		this.linkOut = linkOut;
	}

	public ColfusionLinks(int linkId, int linkAuthor, String linkStatus,
			int linkRandkey, int linkVotes, int linkReports, int linkComments,
			BigDecimal linkKarma, Date linkModified, Date linkDate,
			Date linkPublishedDate, int linkCategory, int linkLang,
			String linkUrl, String linkUrlTitle, String linkTitle,
			String linkTitleUrl, String linkContent, String linkSummary,
			String linkTags, String linkField1, String linkField2,
			String linkField3, String linkField4, String linkField5,
			String linkField6, String linkField7, String linkField8,
			String linkField9, String linkField10, String linkField11,
			String linkField12, String linkField13, String linkField14,
			String linkField15, int linkGroupId, String linkGroupStatus,
			int linkOut) {
		this.linkId = linkId;
		this.linkAuthor = linkAuthor;
		this.linkStatus = linkStatus;
		this.linkRandkey = linkRandkey;
		this.linkVotes = linkVotes;
		this.linkReports = linkReports;
		this.linkComments = linkComments;
		this.linkKarma = linkKarma;
		this.linkModified = linkModified;
		this.linkDate = linkDate;
		this.linkPublishedDate = linkPublishedDate;
		this.linkCategory = linkCategory;
		this.linkLang = linkLang;
		this.linkUrl = linkUrl;
		this.linkUrlTitle = linkUrlTitle;
		this.linkTitle = linkTitle;
		this.linkTitleUrl = linkTitleUrl;
		this.linkContent = linkContent;
		this.linkSummary = linkSummary;
		this.linkTags = linkTags;
		this.linkField1 = linkField1;
		this.linkField2 = linkField2;
		this.linkField3 = linkField3;
		this.linkField4 = linkField4;
		this.linkField5 = linkField5;
		this.linkField6 = linkField6;
		this.linkField7 = linkField7;
		this.linkField8 = linkField8;
		this.linkField9 = linkField9;
		this.linkField10 = linkField10;
		this.linkField11 = linkField11;
		this.linkField12 = linkField12;
		this.linkField13 = linkField13;
		this.linkField14 = linkField14;
		this.linkField15 = linkField15;
		this.linkGroupId = linkGroupId;
		this.linkGroupStatus = linkGroupStatus;
		this.linkOut = linkOut;
	}

	public int getLinkId() {
		return this.linkId;
	}

	public void setLinkId(int linkId) {
		this.linkId = linkId;
	}

	public int getLinkAuthor() {
		return this.linkAuthor;
	}

	public void setLinkAuthor(int linkAuthor) {
		this.linkAuthor = linkAuthor;
	}

	public String getLinkStatus() {
		return this.linkStatus;
	}

	public void setLinkStatus(String linkStatus) {
		this.linkStatus = linkStatus;
	}

	public int getLinkRandkey() {
		return this.linkRandkey;
	}

	public void setLinkRandkey(int linkRandkey) {
		this.linkRandkey = linkRandkey;
	}

	public int getLinkVotes() {
		return this.linkVotes;
	}

	public void setLinkVotes(int linkVotes) {
		this.linkVotes = linkVotes;
	}

	public int getLinkReports() {
		return this.linkReports;
	}

	public void setLinkReports(int linkReports) {
		this.linkReports = linkReports;
	}

	public int getLinkComments() {
		return this.linkComments;
	}

	public void setLinkComments(int linkComments) {
		this.linkComments = linkComments;
	}

	public BigDecimal getLinkKarma() {
		return this.linkKarma;
	}

	public void setLinkKarma(BigDecimal linkKarma) {
		this.linkKarma = linkKarma;
	}

	public Date getLinkModified() {
		return this.linkModified;
	}

	public void setLinkModified(Date linkModified) {
		this.linkModified = linkModified;
	}

	public Date getLinkDate() {
		return this.linkDate;
	}

	public void setLinkDate(Date linkDate) {
		this.linkDate = linkDate;
	}

	public Date getLinkPublishedDate() {
		return this.linkPublishedDate;
	}

	public void setLinkPublishedDate(Date linkPublishedDate) {
		this.linkPublishedDate = linkPublishedDate;
	}

	public int getLinkCategory() {
		return this.linkCategory;
	}

	public void setLinkCategory(int linkCategory) {
		this.linkCategory = linkCategory;
	}

	public int getLinkLang() {
		return this.linkLang;
	}

	public void setLinkLang(int linkLang) {
		this.linkLang = linkLang;
	}

	public String getLinkUrl() {
		return this.linkUrl;
	}

	public void setLinkUrl(String linkUrl) {
		this.linkUrl = linkUrl;
	}

	public String getLinkUrlTitle() {
		return this.linkUrlTitle;
	}

	public void setLinkUrlTitle(String linkUrlTitle) {
		this.linkUrlTitle = linkUrlTitle;
	}

	public String getLinkTitle() {
		return this.linkTitle;
	}

	public void setLinkTitle(String linkTitle) {
		this.linkTitle = linkTitle;
	}

	public String getLinkTitleUrl() {
		return this.linkTitleUrl;
	}

	public void setLinkTitleUrl(String linkTitleUrl) {
		this.linkTitleUrl = linkTitleUrl;
	}

	public String getLinkContent() {
		return this.linkContent;
	}

	public void setLinkContent(String linkContent) {
		this.linkContent = linkContent;
	}

	public String getLinkSummary() {
		return this.linkSummary;
	}

	public void setLinkSummary(String linkSummary) {
		this.linkSummary = linkSummary;
	}

	public String getLinkTags() {
		return this.linkTags;
	}

	public void setLinkTags(String linkTags) {
		this.linkTags = linkTags;
	}

	public String getLinkField1() {
		return this.linkField1;
	}

	public void setLinkField1(String linkField1) {
		this.linkField1 = linkField1;
	}

	public String getLinkField2() {
		return this.linkField2;
	}

	public void setLinkField2(String linkField2) {
		this.linkField2 = linkField2;
	}

	public String getLinkField3() {
		return this.linkField3;
	}

	public void setLinkField3(String linkField3) {
		this.linkField3 = linkField3;
	}

	public String getLinkField4() {
		return this.linkField4;
	}

	public void setLinkField4(String linkField4) {
		this.linkField4 = linkField4;
	}

	public String getLinkField5() {
		return this.linkField5;
	}

	public void setLinkField5(String linkField5) {
		this.linkField5 = linkField5;
	}

	public String getLinkField6() {
		return this.linkField6;
	}

	public void setLinkField6(String linkField6) {
		this.linkField6 = linkField6;
	}

	public String getLinkField7() {
		return this.linkField7;
	}

	public void setLinkField7(String linkField7) {
		this.linkField7 = linkField7;
	}

	public String getLinkField8() {
		return this.linkField8;
	}

	public void setLinkField8(String linkField8) {
		this.linkField8 = linkField8;
	}

	public String getLinkField9() {
		return this.linkField9;
	}

	public void setLinkField9(String linkField9) {
		this.linkField9 = linkField9;
	}

	public String getLinkField10() {
		return this.linkField10;
	}

	public void setLinkField10(String linkField10) {
		this.linkField10 = linkField10;
	}

	public String getLinkField11() {
		return this.linkField11;
	}

	public void setLinkField11(String linkField11) {
		this.linkField11 = linkField11;
	}

	public String getLinkField12() {
		return this.linkField12;
	}

	public void setLinkField12(String linkField12) {
		this.linkField12 = linkField12;
	}

	public String getLinkField13() {
		return this.linkField13;
	}

	public void setLinkField13(String linkField13) {
		this.linkField13 = linkField13;
	}

	public String getLinkField14() {
		return this.linkField14;
	}

	public void setLinkField14(String linkField14) {
		this.linkField14 = linkField14;
	}

	public String getLinkField15() {
		return this.linkField15;
	}

	public void setLinkField15(String linkField15) {
		this.linkField15 = linkField15;
	}

	public int getLinkGroupId() {
		return this.linkGroupId;
	}

	public void setLinkGroupId(int linkGroupId) {
		this.linkGroupId = linkGroupId;
	}

	public String getLinkGroupStatus() {
		return this.linkGroupStatus;
	}

	public void setLinkGroupStatus(String linkGroupStatus) {
		this.linkGroupStatus = linkGroupStatus;
	}

	public int getLinkOut() {
		return this.linkOut;
	}

	public void setLinkOut(int linkOut) {
		this.linkOut = linkOut;
	}

}
