package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated 2014-5-12 21:35:22 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionValidationCode generated by hbm2java
 */
public class ColfusionValidationCode implements java.io.Serializable {

	private ColfusionValidationCodeId id;

	public ColfusionValidationCode() {
	}

	public ColfusionValidationCode(ColfusionValidationCodeId id) {
		this.id = id;
	}

	public ColfusionValidationCodeId getId() {
		return this.id;
	}

	public void setId(ColfusionValidationCodeId id) {
		this.id = id;
	}

}
