package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ColfusionPentahoLogTransformaionId generated by hbm2java
 */
public class ColfusionPentahoLogTransformaionId implements java.io.Serializable {

	private Integer idBatch;
	private String channelId;
	private String transname;
	private String status;
	private Long linesRead;
	private Long linesWritten;
	private Long linesUpdated;
	private Long linesInput;
	private Long linesOutput;
	private Long linesRejected;
	private Long errors;
	private Date startdate;
	private Date enddate;
	private Date logdate;
	private Date depdate;
	private Date replaydate;
	private String logField;

	public ColfusionPentahoLogTransformaionId() {
	}

	public ColfusionPentahoLogTransformaionId(Integer idBatch,
			String channelId, String transname, String status, Long linesRead,
			Long linesWritten, Long linesUpdated, Long linesInput,
			Long linesOutput, Long linesRejected, Long errors, Date startdate,
			Date enddate, Date logdate, Date depdate, Date replaydate,
			String logField) {
		this.idBatch = idBatch;
		this.channelId = channelId;
		this.transname = transname;
		this.status = status;
		this.linesRead = linesRead;
		this.linesWritten = linesWritten;
		this.linesUpdated = linesUpdated;
		this.linesInput = linesInput;
		this.linesOutput = linesOutput;
		this.linesRejected = linesRejected;
		this.errors = errors;
		this.startdate = startdate;
		this.enddate = enddate;
		this.logdate = logdate;
		this.depdate = depdate;
		this.replaydate = replaydate;
		this.logField = logField;
	}

	public Integer getIdBatch() {
		return this.idBatch;
	}

	public void setIdBatch(Integer idBatch) {
		this.idBatch = idBatch;
	}

	public String getChannelId() {
		return this.channelId;
	}

	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

	public String getTransname() {
		return this.transname;
	}

	public void setTransname(String transname) {
		this.transname = transname;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Long getLinesRead() {
		return this.linesRead;
	}

	public void setLinesRead(Long linesRead) {
		this.linesRead = linesRead;
	}

	public Long getLinesWritten() {
		return this.linesWritten;
	}

	public void setLinesWritten(Long linesWritten) {
		this.linesWritten = linesWritten;
	}

	public Long getLinesUpdated() {
		return this.linesUpdated;
	}

	public void setLinesUpdated(Long linesUpdated) {
		this.linesUpdated = linesUpdated;
	}

	public Long getLinesInput() {
		return this.linesInput;
	}

	public void setLinesInput(Long linesInput) {
		this.linesInput = linesInput;
	}

	public Long getLinesOutput() {
		return this.linesOutput;
	}

	public void setLinesOutput(Long linesOutput) {
		this.linesOutput = linesOutput;
	}

	public Long getLinesRejected() {
		return this.linesRejected;
	}

	public void setLinesRejected(Long linesRejected) {
		this.linesRejected = linesRejected;
	}

	public Long getErrors() {
		return this.errors;
	}

	public void setErrors(Long errors) {
		this.errors = errors;
	}

	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public Date getLogdate() {
		return this.logdate;
	}

	public void setLogdate(Date logdate) {
		this.logdate = logdate;
	}

	public Date getDepdate() {
		return this.depdate;
	}

	public void setDepdate(Date depdate) {
		this.depdate = depdate;
	}

	public Date getReplaydate() {
		return this.replaydate;
	}

	public void setReplaydate(Date replaydate) {
		this.replaydate = replaydate;
	}

	public String getLogField() {
		return this.logField;
	}

	public void setLogField(String logField) {
		this.logField = logField;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ColfusionPentahoLogTransformaionId))
			return false;
		ColfusionPentahoLogTransformaionId castOther = (ColfusionPentahoLogTransformaionId) other;

		return ((this.getIdBatch() == castOther.getIdBatch()) || (this
				.getIdBatch() != null && castOther.getIdBatch() != null && this
				.getIdBatch().equals(castOther.getIdBatch())))
				&& ((this.getChannelId() == castOther.getChannelId()) || (this
						.getChannelId() != null
						&& castOther.getChannelId() != null && this
						.getChannelId().equals(castOther.getChannelId())))
				&& ((this.getTransname() == castOther.getTransname()) || (this
						.getTransname() != null
						&& castOther.getTransname() != null && this
						.getTransname().equals(castOther.getTransname())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getLinesRead() == castOther.getLinesRead()) || (this
						.getLinesRead() != null
						&& castOther.getLinesRead() != null && this
						.getLinesRead().equals(castOther.getLinesRead())))
				&& ((this.getLinesWritten() == castOther.getLinesWritten()) || (this
						.getLinesWritten() != null
						&& castOther.getLinesWritten() != null && this
						.getLinesWritten().equals(castOther.getLinesWritten())))
				&& ((this.getLinesUpdated() == castOther.getLinesUpdated()) || (this
						.getLinesUpdated() != null
						&& castOther.getLinesUpdated() != null && this
						.getLinesUpdated().equals(castOther.getLinesUpdated())))
				&& ((this.getLinesInput() == castOther.getLinesInput()) || (this
						.getLinesInput() != null
						&& castOther.getLinesInput() != null && this
						.getLinesInput().equals(castOther.getLinesInput())))
				&& ((this.getLinesOutput() == castOther.getLinesOutput()) || (this
						.getLinesOutput() != null
						&& castOther.getLinesOutput() != null && this
						.getLinesOutput().equals(castOther.getLinesOutput())))
				&& ((this.getLinesRejected() == castOther.getLinesRejected()) || (this
						.getLinesRejected() != null
						&& castOther.getLinesRejected() != null && this
						.getLinesRejected()
						.equals(castOther.getLinesRejected())))
				&& ((this.getErrors() == castOther.getErrors()) || (this
						.getErrors() != null && castOther.getErrors() != null && this
						.getErrors().equals(castOther.getErrors())))
				&& ((this.getStartdate() == castOther.getStartdate()) || (this
						.getStartdate() != null
						&& castOther.getStartdate() != null && this
						.getStartdate().equals(castOther.getStartdate())))
				&& ((this.getEnddate() == castOther.getEnddate()) || (this
						.getEnddate() != null && castOther.getEnddate() != null && this
						.getEnddate().equals(castOther.getEnddate())))
				&& ((this.getLogdate() == castOther.getLogdate()) || (this
						.getLogdate() != null && castOther.getLogdate() != null && this
						.getLogdate().equals(castOther.getLogdate())))
				&& ((this.getDepdate() == castOther.getDepdate()) || (this
						.getDepdate() != null && castOther.getDepdate() != null && this
						.getDepdate().equals(castOther.getDepdate())))
				&& ((this.getReplaydate() == castOther.getReplaydate()) || (this
						.getReplaydate() != null
						&& castOther.getReplaydate() != null && this
						.getReplaydate().equals(castOther.getReplaydate())))
				&& ((this.getLogField() == castOther.getLogField()) || (this
						.getLogField() != null
						&& castOther.getLogField() != null && this
						.getLogField().equals(castOther.getLogField())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdBatch() == null ? 0 : this.getIdBatch().hashCode());
		result = 37 * result
				+ (getChannelId() == null ? 0 : this.getChannelId().hashCode());
		result = 37 * result
				+ (getTransname() == null ? 0 : this.getTransname().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result
				+ (getLinesRead() == null ? 0 : this.getLinesRead().hashCode());
		result = 37
				* result
				+ (getLinesWritten() == null ? 0 : this.getLinesWritten()
						.hashCode());
		result = 37
				* result
				+ (getLinesUpdated() == null ? 0 : this.getLinesUpdated()
						.hashCode());
		result = 37
				* result
				+ (getLinesInput() == null ? 0 : this.getLinesInput()
						.hashCode());
		result = 37
				* result
				+ (getLinesOutput() == null ? 0 : this.getLinesOutput()
						.hashCode());
		result = 37
				* result
				+ (getLinesRejected() == null ? 0 : this.getLinesRejected()
						.hashCode());
		result = 37 * result
				+ (getErrors() == null ? 0 : this.getErrors().hashCode());
		result = 37 * result
				+ (getStartdate() == null ? 0 : this.getStartdate().hashCode());
		result = 37 * result
				+ (getEnddate() == null ? 0 : this.getEnddate().hashCode());
		result = 37 * result
				+ (getLogdate() == null ? 0 : this.getLogdate().hashCode());
		result = 37 * result
				+ (getDepdate() == null ? 0 : this.getDepdate().hashCode());
		result = 37
				* result
				+ (getReplaydate() == null ? 0 : this.getReplaydate()
						.hashCode());
		result = 37 * result
				+ (getLogField() == null ? 0 : this.getLogField().hashCode());
		return result;
	}

}
