package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Feb 28, 2014 5:25:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ColfusionUserroles generated by hbm2java
 */
public class ColfusionUserroles implements java.io.Serializable {

	private int roleId;
	private String role;
	private String description;
	private Set colfusionSourceinfoUsers = new HashSet(0);

	public ColfusionUserroles() {
	}

	public ColfusionUserroles(int roleId, String role) {
		this.roleId = roleId;
		this.role = role;
	}

	public ColfusionUserroles(int roleId, String role, String description,
			Set colfusionSourceinfoUsers) {
		this.roleId = roleId;
		this.role = role;
		this.description = description;
		this.colfusionSourceinfoUsers = colfusionSourceinfoUsers;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getColfusionSourceinfoUsers() {
		return this.colfusionSourceinfoUsers;
	}

	public void setColfusionSourceinfoUsers(Set colfusionSourceinfoUsers) {
		this.colfusionSourceinfoUsers = colfusionSourceinfoUsers;
	}

}
