package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated 2014-5-12 21:35:22 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionAdditionalCategories generated by hbm2java
 */
public class ColfusionAdditionalCategories implements java.io.Serializable {

	private ColfusionAdditionalCategoriesId id;

	public ColfusionAdditionalCategories() {
	}

	public ColfusionAdditionalCategories(ColfusionAdditionalCategoriesId id) {
		this.id = id;
	}

	public ColfusionAdditionalCategoriesId getId() {
		return this.id;
	}

	public void setId(ColfusionAdditionalCategoriesId id) {
		this.id = id;
	}

}
