package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Feb 28, 2014 5:25:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionGroupShared generated by hbm2java
 */
public class ColfusionGroupShared implements java.io.Serializable {

	private Integer shareId;
	private int shareLinkId;
	private int shareGroupId;
	private int shareUserId;

	public ColfusionGroupShared() {
	}

	public ColfusionGroupShared(int shareLinkId, int shareGroupId,
			int shareUserId) {
		this.shareLinkId = shareLinkId;
		this.shareGroupId = shareGroupId;
		this.shareUserId = shareUserId;
	}

	public Integer getShareId() {
		return this.shareId;
	}

	public void setShareId(Integer shareId) {
		this.shareId = shareId;
	}

	public int getShareLinkId() {
		return this.shareLinkId;
	}

	public void setShareLinkId(int shareLinkId) {
		this.shareLinkId = shareLinkId;
	}

	public int getShareGroupId() {
		return this.shareGroupId;
	}

	public void setShareGroupId(int shareGroupId) {
		this.shareGroupId = shareGroupId;
	}

	public int getShareUserId() {
		return this.shareUserId;
	}

	public void setShareUserId(int shareUserId) {
		this.shareUserId = shareUserId;
	}

}
