package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated 2014-6-10 16:17:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ColfusionUserRelationshipVerdict generated by hbm2java
 */
public class ColfusionUserRelationshipVerdict implements java.io.Serializable {

	private ColfusionUserRelationshipVerdictId id;
	private ColfusionUsers colfusionUsers;
	private ColfusionRelationships colfusionRelationships;
	private BigDecimal confidence;
	private String comment;
	private Date when;

	public ColfusionUserRelationshipVerdict() {
	}

	public ColfusionUserRelationshipVerdict(
			ColfusionUserRelationshipVerdictId id,
			ColfusionUsers colfusionUsers,
			ColfusionRelationships colfusionRelationships,
			BigDecimal confidence, Date when) {
		this.id = id;
		this.colfusionUsers = colfusionUsers;
		this.colfusionRelationships = colfusionRelationships;
		this.confidence = confidence;
		this.when = when;
	}

	public ColfusionUserRelationshipVerdict(
			ColfusionUserRelationshipVerdictId id,
			ColfusionUsers colfusionUsers,
			ColfusionRelationships colfusionRelationships,
			BigDecimal confidence, String comment, Date when) {
		this.id = id;
		this.colfusionUsers = colfusionUsers;
		this.colfusionRelationships = colfusionRelationships;
		this.confidence = confidence;
		this.comment = comment;
		this.when = when;
	}

	public ColfusionUserRelationshipVerdictId getId() {
		return this.id;
	}

	public void setId(ColfusionUserRelationshipVerdictId id) {
		this.id = id;
	}

	public ColfusionUsers getColfusionUsers() {
		return this.colfusionUsers;
	}

	public void setColfusionUsers(ColfusionUsers colfusionUsers) {
		this.colfusionUsers = colfusionUsers;
	}

	public ColfusionRelationships getColfusionRelationships() {
		return this.colfusionRelationships;
	}

	public void setColfusionRelationships(
			ColfusionRelationships colfusionRelationships) {
		this.colfusionRelationships = colfusionRelationships;
	}

	public BigDecimal getConfidence() {
		return this.confidence;
	}

	public void setConfidence(BigDecimal confidence) {
		this.confidence = confidence;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getWhen() {
		return this.when;
	}

	public void setWhen(Date when) {
		this.when = when;
	}

}
