package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Feb 24, 2014 10:00:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ColfusionSourceinfoMetadataEditHistory generated by hbm2java
 */
public class ColfusionSourceinfoMetadataEditHistory implements
		java.io.Serializable {

	private String hid;
	private ColfusionSourceinfo colfusionSourceinfo;
	private ColfusionUsers colfusionUsers;
	private Date when;
	private String item;
	private String reason;
	private String value;

	public ColfusionSourceinfoMetadataEditHistory() {
	}

	public ColfusionSourceinfoMetadataEditHistory(String hid,
			ColfusionSourceinfo colfusionSourceinfo,
			ColfusionUsers colfusionUsers, Date when, String item, String value) {
		this.hid = hid;
		this.colfusionSourceinfo = colfusionSourceinfo;
		this.colfusionUsers = colfusionUsers;
		this.when = when;
		this.item = item;
		this.value = value;
	}

	public ColfusionSourceinfoMetadataEditHistory(String hid,
			ColfusionSourceinfo colfusionSourceinfo,
			ColfusionUsers colfusionUsers, Date when, String item,
			String reason, String value) {
		this.hid = hid;
		this.colfusionSourceinfo = colfusionSourceinfo;
		this.colfusionUsers = colfusionUsers;
		this.when = when;
		this.item = item;
		this.reason = reason;
		this.value = value;
	}

	public String getHid() {
		return this.hid;
	}

	public void setHid(String hid) {
		this.hid = hid;
	}

	public ColfusionSourceinfo getColfusionSourceinfo() {
		return this.colfusionSourceinfo;
	}

	public void setColfusionSourceinfo(ColfusionSourceinfo colfusionSourceinfo) {
		this.colfusionSourceinfo = colfusionSourceinfo;
	}

	public ColfusionUsers getColfusionUsers() {
		return this.colfusionUsers;
	}

	public void setColfusionUsers(ColfusionUsers colfusionUsers) {
		this.colfusionUsers = colfusionUsers;
	}

	public Date getWhen() {
		return this.when;
	}

	public void setWhen(Date when) {
		this.when = when;
	}

	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
