package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated 2014-5-12 21:35:22 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionTags generated by hbm2java
 */
public class ColfusionTags implements java.io.Serializable {

	private ColfusionTagsId id;

	public ColfusionTags() {
	}

	public ColfusionTags(ColfusionTagsId id) {
		this.id = id;
	}

	public ColfusionTagsId getId() {
		return this.id;
	}

	public void setId(ColfusionTagsId id) {
		this.id = id;
	}

}
