package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated 2014-5-12 21:35:22 by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionPentahoLogStep generated by hbm2java
 */
public class ColfusionPentahoLogStep implements java.io.Serializable {

	private ColfusionPentahoLogStepId id;

	public ColfusionPentahoLogStep() {
	}

	public ColfusionPentahoLogStep(ColfusionPentahoLogStepId id) {
		this.id = id;
	}

	public ColfusionPentahoLogStepId getId() {
		return this.id;
	}

	public void setId(ColfusionPentahoLogStepId id) {
		this.id = id;
	}

}
