package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Apr 26, 2014 9:30:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionProcesses generated by hbm2java
 */
public class ColfusionProcesses implements java.io.Serializable {

	private Integer pid;
	private String status;
	private String processSer;

	public ColfusionProcesses() {
	}

	public ColfusionProcesses(String status, String processSer) {
		this.status = status;
		this.processSer = processSer;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getProcessSer() {
		return this.processSer;
	}

	public void setProcessSer(String processSer) {
		this.processSer = processSer;
	}

}
