package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Feb 25, 2014 9:55:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * ColfusionUserRelationshipVerdictId generated by hbm2java
 */
public class ColfusionUserRelationshipVerdictId implements java.io.Serializable {

	private int relId;
	private int userId;

	public ColfusionUserRelationshipVerdictId() {
	}

	public ColfusionUserRelationshipVerdictId(int relId, int userId) {
		this.relId = relId;
		this.userId = userId;
	}

	public int getRelId() {
		return this.relId;
	}

	public void setRelId(int relId) {
		this.relId = relId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ColfusionUserRelationshipVerdictId))
			return false;
		ColfusionUserRelationshipVerdictId castOther = (ColfusionUserRelationshipVerdictId) other;

		return (this.getRelId() == castOther.getRelId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRelId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
