package edu.pitt.sis.exp.colfusion.persistence.orm;

// Generated Apr 26, 2014 9:30:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * Statonverdicts generated by hbm2java
 */
public class Statonverdicts implements java.io.Serializable {

	private StatonverdictsId id;

	public Statonverdicts() {
	}

	public Statonverdicts(StatonverdictsId id) {
		this.id = id;
	}

	public StatonverdictsId getId() {
		return this.id;
	}

	public void setId(StatonverdictsId id) {
		this.id = id;
	}

}
